### ISSUE TITLE
can't put myy arms or limbs back on manually

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation13#360]
what the fuck

**Comment by GuyonBroadway** [comment]
Target missing arm with drapes/bedsheet, do prosthetic limb replacement surgery(you can you your old arm) and re attach your arm that way.

**Comment by Spacedong** [comment]
gay

**Comment by JohnGinnane** [comment]
@Spacedong how did it work before?

**Comment by Spacedong** [comment]
you selected the limb and put it back on with your other arm

**Comment by KittyKathy** [comment]
You would literally attach it back on like legos in old code which was stupid as hell but convenient. like if your arm just got blown off in old code you pick it up attach it back on. Which makes it attached to you but not usable it would have its muscles cut like old augmentation code, then use drapes select limb manipulation and use a welding tool or lighter to mend it and that fixes it like brand new.
You actually did not even need to do all that if you used a robot arm because it was buged so if you attached that it would give you back your arm except it was invisible, but no surgery required.

**Comment by JohnGinnane** [comment]
Looks like we need something like https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/modules/surgery/organs/dismemberment_augment.dm#L192

**Comment by Pyko1** [comment]
Actually more of balancing and feature.

As you now need to do proper surgery to attach the blown off limb or cyber limb on to your stump.
